### ISSUE TITLE
[framework][mxnet] Sockeye

### ISSUE THREAD

**Issue by at15** [at15/snowbot#11]
https://github.com/awslabs/sockeye

## TODO

- [x] install locally
- [x] figure out input format
- [ ] run on aws (need to try bigger dataset)
- [ ] clean up old saved model (it has many checkpoints ...)

## Ref

- https://blog.kovalevskyi.com/step-by-step-guide-for-creating-a-chatbot-with-sockeye-mxnet-aws-ec2-and-deeplearning-ami-259f443abf3e

**Comment by at15** [comment]
default parameters give me OOM .... https://github.com/awslabs/sockeye/issues/95

````
[INFO:sockeye.training] Model parameters: att_e2h_weight: (1024, 1024), att_h2s_weight: (1, 1024), att_q2h_weight: (1024, 1024), decoder_rnn_enc2decinit_0_bias: (1024,), decoder_rnn_enc2decinit_0_weight: (1024, 1024), decoder_rnn_enc2decinit_1_bias: (1024,), decoder_rnn_enc2decinit_1_weight: (1024, 1024), decoder_rnn_hidden_bias: (1024,), decoder_rnn_hidden_weight: (1024, 2048), decoder_rnn_l0_h2h_bias: (4096,), decoder_rnn_l0_h2h_weight: (4096, 1024), decoder_rnn_l0_i2h_bias: (4096,), decoder_rnn_l0_i2h_weight: (4096, 1536), encoder_birnn_forward_l0_h2h_bias: (2048,), encoder_birnn_forward_l0_h2h_weight: (2048, 512), encoder_birnn_forward_l0_i2h_bias: (2048,), encoder_birnn_forward_l0_i2h_weight: (2048, 512), encoder_birnn_reverse_l0_h2h_bias: (2048,), encoder_birnn_reverse_l0_h2h_weight: (2048, 512), encoder_birnn_reverse_l0_i2h_bias: (2048,), encoder_birnn_reverse_l0_i2h_weight: (2048, 512), source_embed_weight: (50004, 512), target_embed_weight: (50004, 512), target_output_bias: (50004,), target_output_weight: (50004, 1024)
[INFO:sockeye.training] Total # of parameters: 123450196
[INFO:sockeye.training] Training started.
[INFO:sockeye.callback] Early stopping by optimizing 'perplexity'
[08:41:01] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [08:41:01] src/storage/./pooled_storage_manager.h:102: cudaMalloc failed: out of memory
````

**Comment by at15** [comment]
change rnn-num-hidden to 256 works ...  use 6659 MB (should be around 5GB ... other used by system)

````
[INFO:sockeye.model] Saved config to "/home/at15/workspace/src/github.com/at15/snowbot/model/mxnet_sockeye/config"
[INFO:sockeye.training] Model parameters: att_e2h_weight: (256, 256), att_h2s_weight: (1, 256), att_q2h_weight: (256, 256), decoder_rnn_enc2decinit_0_bias: (256,), decoder_rnn_enc2decinit_0_weight: (256, 256), decoder_rnn_enc2decinit_1_bias: (256,), decoder_rnn_enc2decinit_1_weight: (256, 256), decoder_rnn_hidden_bias: (256,), decoder_rnn_hidden_weight: (256, 512), decoder_rnn_l0_h2h_bias: (1024,), decoder_rnn_l0_h2h_weight: (1024, 256), decoder_rnn_l0_i2h_bias: (1024,), decoder_rnn_l0_i2h_weight: (1024, 768), encoder_birnn_forward_l0_h2h_bias: (512,), encoder_birnn_forward_l0_h2h_weight: (512, 128), encoder_birnn_forward_l0_i2h_bias: (512,), encoder_birnn_forward_l0_i2h_weight: (512, 512), encoder_birnn_reverse_l0_h2h_bias: (512,), encoder_birnn_reverse_l0_h2h_weight: (512, 128), encoder_birnn_reverse_l0_i2h_bias: (512,), encoder_birnn_reverse_l0_i2h_weight: (512, 512), source_embed_weight: (50004, 512), target_embed_weight: (50004, 512), target_output_bias: (50004,), target_output_weight: (50004, 256)
[INFO:sockeye.training] Total # of parameters: 66157396
[INFO:sockeye.training] Training started.
[INFO:sockeye.callback] Early stopping by optimizing 'perplexity'
[INFO:root] Epoch[0] Batch [50]	Speed: 375.31 samples/sec	perplexity=10827.942326
````

**Comment by at15** [comment]
````sh
python -m sockeye.translate --models /home/at15/workspace/src/github.com/at15/snowbot/model/mxnet_sockeye
````

**Comment by at15** [comment]
now we got a .... snowbot++, I don't know and I don't want to talk to you .... and a question bot ....

`````
hi
I don't want to talk to you.
what
I don't know.
love
I love you.
fuck
How do you want me to do?
why
I don't know.
do you have time
I don't want to talk to you.
what's the fuss
I don't know.
come on
What are you talking about?
data
<unk> <unk>
date
I don't want to talk to you.
hu
<unk>
sad
What do you want?
anything else
No.
good to see you
Yeah.
nice to meet you
Yeah.
how are you
I don't know.
like it
I don't want to talk about it.
sure
I don't want to talk about it.
fine
I want to talk to you.
hey
What do you want to do?
good morning
How do you want to do?
good afternoon
What do you want to do?
what is love
I don't know.
life is beautiful
I don't want to talk about it.
coming to terms
I don't want to talk to you. I don't want to talk to you. I don't want to talk to you.
so far
<unk> <unk>
so good
What do you want to do?
execuse me
What are you talking about?
jack
Yes.
marry
What?
rose
What do you want?
bruce
<unk>
`````

**Comment by at15** [comment]
after removing generic response like I don't know, yes, no .... it's a little bit better 

````
Hi
<unk>
Hello
<unk>
What
<unk>
What is love
i don't want to know what it is.
Do you know why I am here
what do you mean?
What can you tell about this
i don't think so.
Should we go out tonight
i don't want to talk to you.
that's not a good idea 
what do you mean?
Have your ever seen your wife, or someone else
what do you mean?
hey bruce    
i don't want to talk to you.
just talk to me
what do you want?
love me
what do you want me to do?
I love you
i don't want to see you.
i love you
i love you.
come and get it
what do you want?
do you know
i don't think so.
this is much more than i can handle
i don't want to know what it is.
is this all you got
i don't think so.
like father like son
what do you mean?
the moon looks great tonight
i don't want to go to the <unk>
do you have time on friday night
i don't want to talk to you.
this is the last time you talk to me like this
i don't want to talk to you.
love it or not
what do you want me to do?
like it or not
what do you want me to do?
how about going out friday night
i don't want to talk to you.
that's all
what do you want?
execuse me?
what?
what?
what do you want?
why?
because i don't want to see you.
show me 
i don't want to see you.
show me the meaning
what are you going to do?
i am going to play movie and watch movie
what are you going to do?
what am I doning now
i don't want to know what it is.
what are you doing now
what do you want?
i want to see you
i don't want to talk to you.
that is a shame
i don't think so.
i don't think so
what do you want to do?
what do you want to do
i don't want to see you.
`````

**Comment by at15** [comment]
the twitter data seems to be better .... it can detect her, him and response with she, he, mxnet_sockeye_twitter_1209_01

`````
hello
<unk>
what are you doing
i have no idea what i was talking about
do you love him
i think he is a <unk>
what is love
i love you so much
i don't know that
i don't know what you did with me
like father like son
this is the best part of the <unk>
have you seen the movie
i thought it was a <unk>
it's much better than that
i don't know what i was talking about
trump
<unk> <unk>
president
<unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk>
what are you doing today
i don't know what i was in the <unk>
coming out of dark
i love you <unk>
this is amazing
thank you so much <unk>
thank you
thank you so much ❤️
no
<unk>
yes
<unk>
what should I do
<unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk>
what should i do
i don't know what you want to do with the <unk>
what should you do
i have no idea what it is.
what do you think about him
i think he is a <unk>
what do you think about her
i think she is a <unk>
i like what you said
i don't know what you did with me
do you know where to find a nice restaurant
i have no idea what i was in the <unk>
keep in touch
thank you so much!!
[INFO:__main__] Processed 24 lines in 24 batches. Total time: 1.6032, sec/sent: 0.0668, sent/sec: 14.9698
[INFO:sockeye.utils] Releasing GPU 0.
`````
